@echo on
for /f "delims=" %%i in ('git rev-list --count HEAD') do set ForetrexToolboxRev=%%i
echo // auto generated by pre build step > Version.cs
echo [assembly: System.Reflection.AssemblyVersion("1.0.0.%ForetrexToolboxRev%")] >> Version.cs

