//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace ForetrexToolbox.KML
{
  using System.Xml.Serialization;


  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/kml/2.2")]
  [System.Xml.Serialization.XmlRootAttribute("kml", Namespace = "http://www.opengis.net/kml/2.2", IsNullable = false)]
  public partial class kmlType
  {

    private documentType documentField;

    /// <remarks/>
    public documentType Document
    {
      get
      {
        return this.documentField;
      }
      set
      {
        this.documentField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/kml/2.2")]
  public partial class documentType
  {

    private string nameField;

    private string descriptionField;

    private placemarkType[] placemarkField;

    /// <remarks/>
    public string name
    {
      get
      {
        return this.nameField;
      }
      set
      {
        this.nameField = value;
      }
    }

    /// <remarks/>
    public string description
    {
      get
      {
        return this.descriptionField;
      }
      set
      {
        this.descriptionField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Placemark")]
    public placemarkType[] Placemark
    {
      get
      {
        return this.placemarkField;
      }
      set
      {
        this.placemarkField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/kml/2.2")]
  public partial class placemarkType
  {

    private lineStringType lineStringField;

    /// <remarks/>
    public lineStringType LineString
    {
      get
      {
        return this.lineStringField;
      }
      set
      {
        this.lineStringField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/kml/2.2")]
  public partial class lineStringType
  {

    private string coordinatesField;

    /// <remarks/>
    public string coordinates
    {
      get
      {
        return this.coordinatesField;
      }
      set
      {
        this.coordinatesField = value;
      }
    }
  }
}
