//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace ForetrexToolbox.Gpx10
{
  using System.Xml.Serialization;


  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.groundspeak.com/cache/1/0/1")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.groundspeak.com/cache/1/0/1", IsNullable = false)]
  public partial class cache
  {

    private string nameField;

    private string placed_byField;

    private cacheOwner[] ownerField;

    private string typeField;

    private string containerField;

    private cacheAttributes[] attributesField;

    private string difficultyField;

    private string terrainField;

    private string countryField;

    private string stateField;

    private cacheShort_description[] short_descriptionField;

    private cacheLong_description[] long_descriptionField;

    private string encoded_hintsField;

    private cacheLogs[] logsField;

    private cacheTravelbugs[] travelbugsField;

    private string idField;

    private string availableField;

    private string archivedField;

    /// <remarks/>
    public string name
    {
      get
      {
        return this.nameField;
      }
      set
      {
        this.nameField = value;
      }
    }

    /// <remarks/>
    public string placed_by
    {
      get
      {
        return this.placed_byField;
      }
      set
      {
        this.placed_byField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("owner", IsNullable = true)]
    public cacheOwner[] owner
    {
      get
      {
        return this.ownerField;
      }
      set
      {
        this.ownerField = value;
      }
    }

    /// <remarks/>
    public string type
    {
      get
      {
        return this.typeField;
      }
      set
      {
        this.typeField = value;
      }
    }

    /// <remarks/>
    public string container
    {
      get
      {
        return this.containerField;
      }
      set
      {
        this.containerField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("attributes")]
    public cacheAttributes[] attributes
    {
      get
      {
        return this.attributesField;
      }
      set
      {
        this.attributesField = value;
      }
    }

    /// <remarks/>
    public string difficulty
    {
      get
      {
        return this.difficultyField;
      }
      set
      {
        this.difficultyField = value;
      }
    }

    /// <remarks/>
    public string terrain
    {
      get
      {
        return this.terrainField;
      }
      set
      {
        this.terrainField = value;
      }
    }

    /// <remarks/>
    public string country
    {
      get
      {
        return this.countryField;
      }
      set
      {
        this.countryField = value;
      }
    }

    /// <remarks/>
    public string state
    {
      get
      {
        return this.stateField;
      }
      set
      {
        this.stateField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("short_description", IsNullable = true)]
    public cacheShort_description[] short_description
    {
      get
      {
        return this.short_descriptionField;
      }
      set
      {
        this.short_descriptionField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("long_description", IsNullable = true)]
    public cacheLong_description[] long_description
    {
      get
      {
        return this.long_descriptionField;
      }
      set
      {
        this.long_descriptionField = value;
      }
    }

    /// <remarks/>
    public string encoded_hints
    {
      get
      {
        return this.encoded_hintsField;
      }
      set
      {
        this.encoded_hintsField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("logs")]
    public cacheLogs[] logs
    {
      get
      {
        return this.logsField;
      }
      set
      {
        this.logsField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("travelbugs")]
    public cacheTravelbugs[] travelbugs
    {
      get
      {
        return this.travelbugsField;
      }
      set
      {
        this.travelbugsField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id
    {
      get
      {
        return this.idField;
      }
      set
      {
        this.idField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string available
    {
      get
      {
        return this.availableField;
      }
      set
      {
        this.availableField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string archived
    {
      get
      {
        return this.archivedField;
      }
      set
      {
        this.archivedField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.groundspeak.com/cache/1/0/1")]
  public partial class cacheOwner
  {

    private string idField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id
    {
      get
      {
        return this.idField;
      }
      set
      {
        this.idField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
      get
      {
        return this.valueField;
      }
      set
      {
        this.valueField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.groundspeak.com/cache/1/0/1")]
  public partial class cacheAttributes
  {

    private object dummyField;

    private cacheAttributesAttribute[] attributeField;

    /// <remarks/>
    public object dummy
    {
      get
      {
        return this.dummyField;
      }
      set
      {
        this.dummyField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("attribute", IsNullable = true)]
    public cacheAttributesAttribute[] attribute
    {
      get
      {
        return this.attributeField;
      }
      set
      {
        this.attributeField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.groundspeak.com/cache/1/0/1")]
  public partial class cacheAttributesAttribute
  {

    private string idField;

    private sbyte incField;

    private bool incFieldSpecified;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id
    {
      get
      {
        return this.idField;
      }
      set
      {
        this.idField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public sbyte inc
    {
      get
      {
        return this.incField;
      }
      set
      {
        this.incField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool incSpecified
    {
      get
      {
        return this.incFieldSpecified;
      }
      set
      {
        this.incFieldSpecified = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
      get
      {
        return this.valueField;
      }
      set
      {
        this.valueField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.groundspeak.com/cache/1/0/1")]
  public partial class cacheShort_description
  {

    private string htmlField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string html
    {
      get
      {
        return this.htmlField;
      }
      set
      {
        this.htmlField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
      get
      {
        return this.valueField;
      }
      set
      {
        this.valueField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.groundspeak.com/cache/1/0/1")]
  public partial class cacheLong_description
  {

    private string htmlField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string html
    {
      get
      {
        return this.htmlField;
      }
      set
      {
        this.htmlField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
      get
      {
        return this.valueField;
      }
      set
      {
        this.valueField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.groundspeak.com/cache/1/0/1")]
  public partial class cacheLogs
  {

    private object dummyField;

    private cacheLogsLog[] logField;

    /// <remarks/>
    public object dummy
    {
      get
      {
        return this.dummyField;
      }
      set
      {
        this.dummyField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("log")]
    public cacheLogsLog[] log
    {
      get
      {
        return this.logField;
      }
      set
      {
        this.logField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.groundspeak.com/cache/1/0/1")]
  public partial class cacheLogsLog
  {

    private string dateField;

    private string typeField;

    private cacheLogsLogFinder[] finderField;

    private cacheLogsLogText[] textField;

    private cacheLogsLogLog_wpt[] log_wptField;

    private string idField;

    /// <remarks/>
    public string date
    {
      get
      {
        return this.dateField;
      }
      set
      {
        this.dateField = value;
      }
    }

    /// <remarks/>
    public string type
    {
      get
      {
        return this.typeField;
      }
      set
      {
        this.typeField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("finder", IsNullable = true)]
    public cacheLogsLogFinder[] finder
    {
      get
      {
        return this.finderField;
      }
      set
      {
        this.finderField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("text", IsNullable = true)]
    public cacheLogsLogText[] text
    {
      get
      {
        return this.textField;
      }
      set
      {
        this.textField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("log_wpt")]
    public cacheLogsLogLog_wpt[] log_wpt
    {
      get
      {
        return this.log_wptField;
      }
      set
      {
        this.log_wptField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id
    {
      get
      {
        return this.idField;
      }
      set
      {
        this.idField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.groundspeak.com/cache/1/0/1")]
  public partial class cacheLogsLogFinder
  {

    private string idField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id
    {
      get
      {
        return this.idField;
      }
      set
      {
        this.idField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
      get
      {
        return this.valueField;
      }
      set
      {
        this.valueField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.groundspeak.com/cache/1/0/1")]
  public partial class cacheLogsLogText
  {

    private string encodedField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string encoded
    {
      get
      {
        return this.encodedField;
      }
      set
      {
        this.encodedField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
      get
      {
        return this.valueField;
      }
      set
      {
        this.valueField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.groundspeak.com/cache/1/0/1")]
  public partial class cacheLogsLogLog_wpt
  {

    private string latField;

    private string lonField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string lat
    {
      get
      {
        return this.latField;
      }
      set
      {
        this.latField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string lon
    {
      get
      {
        return this.lonField;
      }
      set
      {
        this.lonField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.groundspeak.com/cache/1/0/1")]
  public partial class cacheTravelbugs
  {

    private object dummyField;

    private cacheTravelbugsTravelbug[] travelbugField;

    /// <remarks/>
    public object dummy
    {
      get
      {
        return this.dummyField;
      }
      set
      {
        this.dummyField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("travelbug")]
    public cacheTravelbugsTravelbug[] travelbug
    {
      get
      {
        return this.travelbugField;
      }
      set
      {
        this.travelbugField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.groundspeak.com/cache/1/0/1")]
  public partial class cacheTravelbugsTravelbug
  {

    private string nameField;

    private string idField;

    private string refField;

    /// <remarks/>
    public string name
    {
      get
      {
        return this.nameField;
      }
      set
      {
        this.nameField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id
    {
      get
      {
        return this.idField;
      }
      set
      {
        this.idField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string @ref
    {
      get
      {
        return this.refField;
      }
      set
      {
        this.refField = value;
      }
    }
  }
}
